<HomeScreen>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10



        BoxLayout:
            orientation: 'horizontal'
            Label:
                text: "Prompting"
            Button:
                text: "Settings"
                on_press: root.manager.current = 'settings'

        TextInput:
            id: prompt_start
            multiline: True
            hint_text: "Enter, a, prompt, here"

        BoxLayout:
            orientation: 'horizontal'

            BoxLayout:
                orientation: 'vertical'

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        text: "Weighted"
                    CheckBox:
                        id: checkbox_weighted
                        active: True

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        text: "Randomized"
                    CheckBox:
                        id: checkbox_randomized
                        active: True

            Button:
                text: "Create"
                on_press: root.on_button_create()

            Button:
                text: "Copy to clipboard"
                on_press: root.on_button_copy()

        TextInput:
            id: prompt_new
            multiline: True

<SettingsScreen>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10

        BoxLayout:
            orientation: 'horizontal'
            Label:
                text: "Settings"
            Button:
                text: "Home"
                on_press: root.manager.current = 'home'