WindowManager:
    HomeScreen:
    SettingsScreen:

<HomeScreen>
    name: "home"

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10

        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.25)
            Label:
                text: "Prompting"
            Button:
                text: "Settings"
                on_press:
                    root.manager.current = 'settings'
                    root.manager.transition.direction = 'left'

        TextInput:
            id: prompt_start
            multiline: True
            hint_text: "Enter, a, prompt, here"

        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1, 0.25)

            Button:
                text: "Clear"
                on_release: root.on_button_clear()

            Button:
                text: "Create"
                on_press: root.on_button_create()

            Button:
                text: "Copy to clipboard"
                on_press: root.on_button_copy()

        TextInput:
            id: prompt_new
            multiline: True

<SettingsScreen>
    name: "settings"

    chk_weighted: chk_weighted
    chk_randomized: chk_randomized

    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        padding: 10
        spacing: 10

        BoxLayout:
            orientation: 'horizontal'
            Label:
                text: "Settings"
            Button:
                text: "Home"
                on_press:
                    root.manager.current = 'home'
                    root.manager.transition.direction = 'right'

        BoxLayout:
            orientation: 'horizontal'

            BoxLayout:
                orientation: 'vertical'

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        text: "Weighted"
                    CheckBox:
                        id: chk_weighted
                        active: True

                BoxLayout:
                    orientation: 'horizontal'

                    Label:
                        text: "Randomized"
                    CheckBox:
                        id: chk_randomized
                        active: True